org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.home=D:\\OAPP\\Android Studio\\jbr
kotlin.code.style=official
kotlin.cpp.standalone=true
android.useAndroidX=true
android.nonTransitiveRClass=true
# MIUIX 0.9.2 要求 compileSdk 37，当前 AGP 8.13.0 仅官方测试到 36
android.suppressUnsupportedCompileSdk=37.0
# Windows 主机无法运行 iOS/macOS 模拟器测试，忽略不可用的原生目标
kotlin.native.ignoreDisabledTargets=true
org.jetbrains.compose.experimental.macos.enabled=true
